# Generated by Django 3.2.7 on 2022-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
